// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFyrr-hTkPnKxXzlAcSvZtxR7UK-xupuU',
    appId: '1:1088652815015:web:ba41e34b6d43c68a1d4982',
    messagingSenderId: '1088652815015',
    projectId: 'parkingapp-a4132',
    authDomain: 'parkingapp-a4132.firebaseapp.com',
    storageBucket: 'parkingapp-a4132.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASnANP3wh0EV3uPmkL_sJBZlphglzi4ls',
    appId: '1:1088652815015:android:2f05b55dc9bf61b01d4982',
    messagingSenderId: '1088652815015',
    projectId: 'parkingapp-a4132',
    storageBucket: 'parkingapp-a4132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy2Vc2ubrQJzOCfwDFhqve6N_LyeS6xK0',
    appId: '1:1088652815015:ios:43509df8dd4560c91d4982',
    messagingSenderId: '1088652815015',
    projectId: 'parkingapp-a4132',
    storageBucket: 'parkingapp-a4132.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );
}
